version: '3.9'
services:
  library:
    image: test_link_tic:latest
    container_name: test_link_tic
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
